[build]
  command = ""
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/api/auth/signin"
  to = "/.netlify/functions/auth-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql-proxy"
  status = 200
  force = true
